version: "2"
networks:
  caddy:
    external: true
services:
  app:
    build:
      context: ../
    image: chat-ai-backend
    ports: ["3001:3001", "3002:3002"]
    networks: ["caddy"]
    labels:
      caddy: aichatapi.lebroncode.com
      caddy.reverse_proxy: "{{upstreams 3001}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks: ["caddy"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/caddy-data:/data
    restart: unless-stopped
